# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSWwNFL6zAPw-nmoDZxSmxYdj4kGNLWO
"""

class Carro:
    def __init__ (self, modelo, dono, quilometragem):
        self.modelo = modelo
        self.__dono = dono
        self.quilometragem = quilometragem

    def donoSet(self, dono):
        self.__dono = dono

    def donoGet(self):
        return self.__dono

    def __str__(self):
        return f"Modelo: {self.modelo}\nDono: {self.__dono}\nQuilometragem: {self.quilometragem} km"

    def __repr__(self):
        return f"Modelo: {self.modelo}\nDono: {self.__dono}\nQuilometragem: {self.quilometragem} km"

carro = Carro("fiat_500", "pedro", 10000)
print(carro)

carro.donoSet("joão")#demons
print(carro)
